#! /bin/sh

sxhkd &

#give 0 desktops to laptop monitor 
dp1=$(xrandr --query | grep 'DP-1-1')
dp2=$(xrandr --query | grep 'DP-2-1-8')
if [[ $dp1 = *connected* ]] && [[ $dp2 = *connected* ]]; then
    bspc monitor eDP-1 -d
    bspc monitor DP-2-1-8 -d 6 7 8 9 0 
    bspc monitor DP-1-1 -d 1 2 3 4 5
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
fi


bspc config border_width         3
bspc config window_gap           7
bspc config bottom_padding 35

bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false
bspc config history_aware_focus           true
bspc config remove_unplugged_monitors     true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#458ade"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

